### PR TITLE
dont expand glob for resources attribute

### PR DESCRIPTION
**Pull request by hborawski**
As outlined in slack -> https://bazelbuild.slack.com/archives/CD3QY5C2X/p1638825357038200

```ruby
someSpec.resources = 'path/to/folder`
```

Works fine in cocoapods and in Xcode, importing the folder, but was erroring out when building with bazel after generating with this plugin:
```sh
I/O exception during sandboxed execution: /private/var/tmp/_bazel_hborawski/1f6df4ad563028a25ba3a2ddabdedf60/sandbox/darwin-sandbox/897/execroot/<path/to/folder> (File exists)
```

Turns out it was `expand_glob` duplicating the path like:
```starlark
data = glob([
            "path/to/folder",
            "path/to/folder/**/*",
```

### CODE REVIEW

**Comment by chenxiao0228** [comment]
Thanks @hborawski !

Any chance you could add a test case for it?

**Comment by hborawski** [comment]
@chenxiao0228 There's an unrelated failure for me even running tests on master, but i _think_ i added a case for it correctly?

I added a before/after for an app_spec using `resources`

**Comment by chenxiao0228** [comment]
@hborawski  sorry my bad.. I'll take a look into the checks.

**Comment by hborawski** [comment]
hmm im actually now not convinced this is the correct fix

some paths included in `resources` do need the expansion i think

i dont have issues with `.xcassets` expanding in the BUILD

```starlark
data = glob(
            [
                "App/Resources/**/*.storyboard",
                "App/Resources/**/*.storyboard/**/*",
                "App/Resources/**/*.xib",
                "App/Resources/**/*.xib/**/*",
                "App/Resources/**/*.xcassets",
                "App/Resources/**/*.xcassets/**/*",
            ],
            exclude_directories = 0,
        ),
```

builds fine, but if i try to include a folder of JSON files, it behaves improperly

**Comment by hborawski** [comment]
I think this is actually caused by: https://github.com/bazel-ios/rules_ios/blob/8c3c7fe77ff69bbbe8861eed53ecf82461979ebc/rules/library/resources.bzl#L59

**Pull request closed without merging**
